export enum MusicType {
  PIANO = 'PIANO',
  KEYBOARD = 'KEYBOARD',
  RECORDER = 'RECORDER',
  CLASSICAL_GUITAR = 'CLASSICAL_GUITAR',
  DRUM = 'DRUM',
  ELECTRIC_GUITAR = 'ELECTRIC_GUITAR',
  VIOLIN = 'VIOLIN',
  BASS_GUITAR = 'BASS_GUITAR',
  SAXOPHONE = 'SAXOPHONE',
  FLUTE = 'FLUTE',
  CELLO = 'CELLO',
  CLARINET = 'CLARINET',
  TRUMPET = 'TRUMPET',
  HARP = 'HARP',
  MIX = 'MIX'
}
